# Configuración de base de datos para Desarrollo (Local PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_productos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA para Desarrollo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Secret JWT para desarrollo local
jwt.secret=LALLAVESUPERSECRETADELOSPRODUCTOSYUSAIORSDELSISTEMA123456
